twig:
    file_name_pattern: '*.twig'
    globals: 
        api_key: 'TOTO_JE_TAJNY_API_KLIC'
        highlander: '@App\Service\Highlander'
    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true
