# highlander_says:
#     path: /weather/{treshold<\d+>?50}
#     controller: App\Controller\WeatherController::index

# highlander_guess:
#     path: /weather/{guess}
#     controller: App\Controller\WeatherController::indexGuess
